using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace DocMgr
{
    public partial class FormCreateDoc : Form
    {
        string folderForDoc;
        string docName = "";
        string filePath = "";

        public string FolderForDoc { get => folderForDoc; set => folderForDoc = value; }
        public string DocName { get => docName; set => docName = value; }
        public string FilePath { get => filePath; set => filePath = value; }

        public FormCreateDoc(string initialFolder = @"C:\")
        {
            InitializeComponent();
            buttonClose.Enabled = true;
            FolderForDoc = initialFolder;
            labelPath.Text = FolderForDoc;
            CenterToScreen();
            DocMgr.CenterCursor();
            //DFW: textBoxDocName.Focus();
            textBoxDocName.Select();
        }

        private void buttonSelect_Click(object sender, EventArgs e)
        {
            string folder = FolderSelector.SelectFolder();
            if (folder != null)
            {
                FolderForDoc = folder;          // Save user's selection:
                labelPath.Text = FolderForDoc;
            }
        }

        private void buttonCreate_Click(object sender, EventArgs e)
        {
            DocName = textBoxDocName.Text;
            FilePath = labelPath.Text + "\\" + DocName + ".rtf";

            if (File.Exists(FilePath))
            {
                DocName = "";
                MessageBox.Show("File " + FilePath + " already exists.");
                return;
            }

            using (FileStream fs = File.Create(FilePath))
            using (var sw = new StreamWriter(fs))
            {                                               // Empty RTF file:
                sw.Write(@"{\rtf1\ansi\deff0 {\fonttbl {\f0 fnil Arial; }}\pard\f0\fs20\par}");
                DialogResult = DialogResult.OK;
                Close();
            }
        }

        private void buttonClose_Click(object sender, EventArgs e)
        {
            Close();
        }

        private void FormCreateDoc_KeyPress(object sender, KeyPressEventArgs e)
        {
            if (e.KeyChar == (int)Keys.Escape)
            {
                e.Handled = true;
                buttonClose_Click(sender, e);           // User wants to exit.
            }
        }

        private void textBoxDocName_TextChanged(object sender, EventArgs e)
        {
            buttonCreate.Enabled = textBoxDocName.Text.Length > 0;
        }

        private void FormCreateDoc_Shown(object sender, EventArgs e)
        {
            buttonCreate.CenterCursorInButton(0, 5);          // This has to be done after the ctor.
        }
    }

    public class FolderSelector     // Generated by ChatGPT.
    {
        public static string SelectFolder()
        {
            using (FolderBrowserDialog dialog = new FolderBrowserDialog())
            {
                dialog.Description = "Select Folder For New Document";
                dialog.ShowNewFolderButton = true;

                if (dialog.ShowDialog() == DialogResult.OK)
                {
                    return dialog.SelectedPath;
                }
            }
            return null; // Return null if no folder was selected
        }
    }

}
