using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace DocMgr
{
    public partial class FormCreateDoc : Form
    {
        string folderForDoc;
        string docName = "";
        string filePath = "";

        public string FolderForDoc { get => folderForDoc; set => folderForDoc = value; }
        public string DocName { get => docName; set => docName = value; }
        public string FilePath { get => filePath; set => filePath = value; }

        public FormCreateDoc(string initialFolder = @"C:\")
        {
            InitializeComponent();
            buttonClose.Enabled = true;
            buttonSelect.CenterCursorInButton();
            FolderForDoc = initialFolder;
            labelPath.Text = FolderForDoc;
            CenterToScreen();
            DocMgr.CenterCursor();
            //DFW: textBoxDocName.Focus();
            textBoxDocName.Select();
        }

        //private void CenterCursor(int xOffset = 0, int yOffset = 0)
        //{
        //    Cursor.Position = new Point(Screen.PrimaryScreen.Bounds.Width / 2 + xOffset,
        //        Screen.PrimaryScreen.Bounds.Height / 2 + yOffset);
        //}

        private void buttonSelect_Click(object sender, EventArgs e)
        {
            string folder = FolderSelector.SelectFolder();
            if (folder != null)
            {
                FolderForDoc = folder;          // Save user's selection:
                labelPath.Text = FolderForDoc;
            }
        }

        private void buttonCreate_Click(object sender, EventArgs e)
        {
            DocName = textBoxDocName.Text;
            FilePath = labelPath.Text + "\\" + DocName + ".rtf";

            if (File.Exists(FilePath))
            {
                DocName = "";
                MessageBox.Show("File " + FilePath + " already exists.");
                return;
            }

            using (FileStream fs = File.Create(FilePath))
            using (var sw = new StreamWriter(fs))
            {                                           // Crude kludge.  C# malfunctions saving blank RTF file.
                sw.Write(@"{\rtf1\ansi\ansicpg1252\deff0\nouicompat\deflang1033{\fonttbl{\f0\b1\fnil\fcharset0 Calibri;}}\
{\*\generator Riched20 10.0.22621}\viewkind4\uc1\
\pard\sa200\sl276\slmult1\f0\b1\fs22\lang9\par\
}");
                DialogResult = DialogResult.OK;
                Close();
            }
        }

        private void buttonClose_Click(object sender, EventArgs e)
        {
            Close();
        }

        private void FormCreateDoc_KeyPress(object sender, KeyPressEventArgs e)
        {
            if (e.KeyChar == (int)Keys.Escape)
                buttonClose_Click(sender, e);           // User wants to exit.
        }

        private void textBoxDocName_TextChanged(object sender, EventArgs e)
        {
            buttonCreate.Enabled = textBoxDocName.Text.Length > 0;
        }
    }

    public class FolderSelector     // Generated by ChatGPT.
    {
        public static string SelectFolder()
        {
            using (FolderBrowserDialog dialog = new FolderBrowserDialog())
            {
                dialog.Description = "Select Folder For New Document";
                dialog.ShowNewFolderButton = true;

                if (dialog.ShowDialog() == DialogResult.OK)
                {
                    return dialog.SelectedPath;
                }
            }
            return null; // Return null if no folder was selected
        }
    }
}
